FROM n8nio/n8n:latest

# (Opsional) Jika butuh dependensi tambahan, tambahkan di bawah ini
# RUN apt-get update && apt-get install -y <package>

# Forward port
EXPOSE 5678

# (Opsional) Custom CMD jika perlu, default-nya sudah menjalankan n8n
# CMD ["n8n"]
