name: Coffeepoint CI

on:
  push:
    branches:
      - main
      - backend
      - frontend
  pull_request:
    branches:
      - main
      - backend
      - frontend

jobs:
  backend:
    name: Backend - FastAPI CI
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/backend' || github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run FastAPI check (you can modify this)
        run: |
          uvicorn main:app --reload --host 0.0.0.0 --port 8000
          echo "Backend check complete."
          # Bisa diganti dengan: pytest, uvicorn --check, dll

  frontend:
    name: Frontend - React CI
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/frontend' || github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run frontend build
        run: npm run build
