name: Coffeepoint CI

on:
  push:
    branches:
      - main
      - backend
      - frontend
  pull_request:
    branches:
      - main
      - backend
      - frontend

jobs:
  backend:
    name: Backend - FastAPI CI
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/backend' || github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Create virtual environment & install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate firebase credentials file
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
        run: |
          echo "$FIREBASE_CREDENTIALS" > coffeepoint2.json

      - name: Run backend check
        run: |
          source venv/bin/activate
          echo "Backend check complete."
          # Contoh jika mau run test:
          # pytest

  frontend:
    name: Frontend - React CI
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/frontend' || github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run frontend build
        run: npm run build
